# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17b40c7e2dad536145c07a6818a89646544db195a7189c50ce17711c0622313bc82bd6a986408fb9cbbded94c53d0850407decdfd4426540ed2efa55f4d95f84

test:
  secret_key_base: f4dfce4d27c97ef752c4e09204e70a855eea4cc20c59ced276509a8cc228033b43d611fe5935438b7143847666be7f78e46aae65ecd690ebcf6a18e79f7c74b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
